# For Python 3.11
FROM python:3.11-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Ensuring necessary components are installed for library compilation
# RUN apk add --no-cache \
#     build-base \
#     libffi-dev \
#     python3-dev

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy our API file.
COPY ./src/main.py .

# docker build -f Dockerfile.fastapi -t image_upload_api .
# docker run -p 3030:3030 -v /Volumes/JosueSSD/mac\ latest\ documents/react-projects/image_uploader/src:/app image_upload_api uvicorn main:app --host 0.0.0.0 --port 3030 --reload